

# This file was *autogenerated* from the file ../healthcheck/solve.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_10 = Integer(10); _sage_const_2 = Integer(2)#!/usr/bin/env python3

from pwn import *
import random

server = process("./server.py")
# server = remote("127.0.0.1", 1337)

"""
	Get time-released crypto challenge 
"""
server.recvuntil(b"Here is your random token: ")
token = int(server.recvline().decode().strip())
server.recvuntil(b"The public modulus is: ")
n = int(server.recvline().decode().strip())
server.recvuntil(b"times exponentiation to get the valid ticket ")
_ = server.recvuntil(" % n!")
d = int(_.decode().split("2^(2^")[_sage_const_1 ].split("))")[_sage_const_0 ])

"""
	Query the oracle and setup the HNP
"""
DELTA = _sage_const_0 
def query(server, u):
	server.sendlineafter(b">>>", b"1")
	server.sendlineafter(b"Tell me the token. ", str(u).encode())
	server.sendlineafter(b"What is your calculation? ", b"0")
	server.recvuntil(b"Nope, the ans is ")
	_ = server.recvuntil(b"... (")
	MSB = int(_.decode().split("...")[_sage_const_0 ])
	_ = server.recvuntil(b"remain digits")
	lift = int(_.decode().split(" remain digits")[_sage_const_0 ])
	global DELTA
	DELTA = max(DELTA, _sage_const_10 **lift)
	return MSB * (_sage_const_10 **lift)

m = _sage_const_10 
k = m * (m-_sage_const_1 ) // _sage_const_2 
u = [random.randint(_sage_const_2 , n-_sage_const_1 ) for _ in range(m)]
A = [query(server, uu) for uu in u]
B = [query(server, uu * token) for uu in u]
M = Matrix(ZZ, k + _sage_const_2 *m + _sage_const_1 , k + _sage_const_2 *m + _sage_const_1 )
"""
        Inequality we derived by cross-multiplication
"""
idx = _sage_const_0 
for i in range(m):
	for j in range(i+_sage_const_1 , m):
		M[i, idx] = B[j]
		M[j, idx] = -B[i]
		M[i+m, idx] = -A[j]
		M[j+m, idx] = A[i]
		M[_sage_const_2 *m, idx] = A[i]*B[j] - A[j]*B[i]
		M[_sage_const_2 *m+_sage_const_1 +idx, idx] = n
		idx += _sage_const_1 	

"""
	Bound the value of xi and yi
"""
for i in range(_sage_const_2  * m):
	M[i, i+k] = DELTA
M[_sage_const_2 *m, -_sage_const_1 ] = DELTA**_sage_const_2 

M = M.LLL()
for i in range(k+_sage_const_2 *m+_sage_const_1 ):
	if abs(M[i, -_sage_const_1 ]) == DELTA**_sage_const_2 :
		print(f"FOUND! {i}")
		x = [abs(M[i, j] // DELTA) for j in range(k, k+m)]
		y = [abs(M[i, j] // DELTA) for j in range(k+m, k+_sage_const_2 *m)]
		ans = (B[j] + y[j]) * inverse_mod(A[j] + x[j], n) % n
		break

"""
	Capture the flag!
"""
server.sendlineafter(b">>>", b"2")
server.sendlineafter(b"Give me the ticket. ", str(ans).encode())
server.interactive()

