# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
FROM ubuntu:22.04

ENV BUILD_PACKAGES python3-pip build-essential python3-dev
RUN apt-get update \
    && apt-get -yq --no-install-recommends install $BUILD_PACKAGES \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install pwntools

COPY healthcheck_loop.sh healthcheck.py healthz_webserver.py /home/user/
ADD target /home/user/target/
ADD solve /home/user/solve/

WORKDIR /home/user/

CMD /home/user/healthcheck_loop.sh & /home/user/healthz_webserver.py